# Generated by Django 4.2.16 on 2026-03-04 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('occupied', 'Occupied'), ('suspended', 'Suspended')], default='draft', max_length=15)),
                ('gender_type', models.CharField(choices=[('male', 'Men Only'), ('female', 'Women Only'), ('coed', 'Co-ed')], max_length=10)),
                ('meal_option', models.CharField(choices=[('no_meals', 'No Meals'), ('breakfast', 'Breakfast Only'), ('all_meals', 'All Meals')], default='no_meals', max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('locality', models.CharField(db_index=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('price_single', models.PositiveIntegerField(blank=True, help_text='Price per bed/month for single room', null=True)),
                ('price_double', models.PositiveIntegerField(blank=True, null=True)),
                ('price_triple', models.PositiveIntegerField(blank=True, null=True)),
                ('deposit_amount', models.PositiveIntegerField(default=0)),
                ('lock_in_months', models.PositiveSmallIntegerField(default=1)),
                ('total_beds', models.PositiveSmallIntegerField(default=0)),
                ('vacant_beds', models.PositiveSmallIntegerField(default=0)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_geyser', models.BooleanField(default=False)),
                ('has_washing_machine', models.BooleanField(default=False)),
                ('has_cctv', models.BooleanField(default=False)),
                ('has_power_backup', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_lift', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_housekeeping', models.BooleanField(default=False)),
                ('rule_no_smoking', models.BooleanField(default=False)),
                ('rule_no_alcohol', models.BooleanField(default=False)),
                ('curfew_time', models.TimeField(blank=True, null=True)),
                ('guest_policy', models.CharField(blank=True, max_length=255)),
                ('pet_policy', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_inquiries', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='listings.listing')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('tenant', 'listing')},
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', 'locality'], name='listings_li_city_6edd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'gender_type'], name='listings_li_status_2fcfa1_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price_single'], name='listings_li_price_s_9a847b_idx'),
        ),
    ]
