# Generated by Django 4.2.16 on 2026-03-04 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('full_name', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('tenant', 'Tenant'), ('owner', 'PG Owner'), ('admin', 'Admin')], default='tenant', max_length=10)),
                ('profile_photo', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_kyc_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('student_college', models.CharField(blank=True, max_length=255)),
                ('student_course', models.CharField(blank=True, max_length=100)),
                ('student_year', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('office_location', models.CharField(blank=True, max_length=255)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('budget_min', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_max', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_city', models.CharField(blank=True, max_length=100)),
                ('preferred_locality', models.CharField(blank=True, max_length=100)),
                ('gender_preference', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='any', max_length=10)),
                ('meal_preference', models.CharField(choices=[('no_meals', 'No Meals'), ('breakfast', 'Breakfast Only'), ('all_meals', 'All Meals')], default='no_meals', max_length=10)),
                ('owner_city', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('property', 'Property Proof'), ('student_id', 'Student ID'), ('company_id', 'Company ID')], max_length=20)),
                ('doc_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
